#!/bin/bash

if [[ -z `which glue` ]] ; then
    echo "You need to install glue."
    echo "http://glue.readthedocs.org/en/latest/installation.html"
    exit 1
fi

MAKIPATH=$1

if [[ -z $MAKIPATH ]]; then
    echo "Usage: makesprite PATHTOMAKI"
    exit 1
fi


dir=$(dirname $0)
img="$dir/../img"
css="$dir/../css"

glue --namespace=maki --sprite-namespace= $1/renders --css=$css --img=$img
mv $css/renders.css $css/maki.css
mv $img/renders.png $img/maki.png
sed -i 's/renders/maki/' $css/maki.css
