export { operationCircularize } from './circularize';
export { operationFollow } from './follow';
export { operationFollowOld } from './follow_old';
export { operationCurverize } from './curverize';
export { operationCloneAddress } from './clone_address';
export { operationContinue } from './continue';
export { operationDelete } from './delete';
export { operationDisconnect } from './disconnect';
export { operationDowngrade } from './downgrade';
export { operationExtract } from './extract';
export { operationMerge } from './merge';
export { operationMove } from './move';
export { operationOrthogonalize } from './orthogonalize';
export { operationReflectShort, operationReflectLong } from './reflect';
export { operationReverse } from './reverse';
export { operationRotate } from './rotate';
export { operationSplit } from './split';
export { operationStraighten } from './straighten';
