name: Deploy PR Preview

on:
  workflow_run:
    workflows: [build]
    types:
      - completed

permissions:
  contents: read
  actions: write
  deployments: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: workflows
    if: ${{github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
      - run: npm clean-install

      - name: Download all artifacts (dist folder and pr_metadata)
        uses: dawidd6/action-download-artifact@8305c0f1062bb0d184d09ef4493ecb9288447732 # v20
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          run_id: ${{github.event.workflow_run.id}}
          allow_forks: true

      - name: Read pr_metadata
        id: pr_metadata
        run: cat pr_metadata/pr_metadata.ini >> $GITHUB_OUTPUT

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        run: ./node_modules/.bin/netlify deploy --no-build --dir=. --alias=pr-${{steps.pr_metadata.outputs.pr}}

      - name: Run afterDeploy script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { afterDeploy } = await import('${{github.workspace}}/scripts/pr_preview.js');
            await afterDeploy({ core, github, context })(
              '${{steps.pr_metadata.outputs.pr}}',
              '${{steps.pr_metadata.outputs.ref}}',
            );
